# Generated by Django 4.1.4 on 2023-08-03 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sensor Name')),
                ('resolution_type', models.CharField(default='resolution', max_length=30, verbose_name='Resolution Type')),
                ('resolution_value', models.FloatField(default=0, verbose_name='Resolution [m]')),
                ('swath', models.FloatField(default=0, verbose_name='Swath [km]')),
                ('positive_tilting', models.FloatField(default=0, verbose_name='Positive Tilting')),
                ('negative_tilting', models.FloatField(default=0, verbose_name='Negative Tilting')),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('norad_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='NORAD ID')),
                ('name', models.CharField(max_length=20, verbose_name='Satellite Name')),
                ('satellite_type', models.CharField(default='-', max_length=30, verbose_name='Satellite type')),
                ('description', models.TextField(default='-', verbose_name='About Satellite')),
                ('tle', models.TextField(default='', editable=False, verbose_name='Satellite Tle')),
                ('launch_date', models.DateField(default=datetime.datetime(2023, 8, 3, 15, 3, 8, 416081), verbose_name='Launch Date')),
                ('launch_site', models.CharField(default='not provided', max_length=50, verbose_name='Launch Site')),
                ('last_tle_update', models.DateField(default=datetime.datetime(2023, 8, 3, 15, 3, 8, 416081), editable=False, verbose_name='Launch Date')),
                ('swath', models.FloatField(default=0, verbose_name='Swath [km]')),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('not_tracked', 'NOT TRACKED')], default='IN ORBIT', max_length=20, verbose_name='Status')),
                ('orbit', models.CharField(default='-', max_length=20, verbose_name='Orbit Type')),
                ('orbital_period', models.FloatField(default=0, verbose_name='Orbital Period [m]')),
                ('inclination', models.FloatField(default=0, verbose_name='Inclination [°]')),
                ('perigee', models.FloatField(default=0, verbose_name='Perigee')),
                ('apogee', models.FloatField(default=0, verbose_name='Apogee')),
                ('sensors', models.ManyToManyField(to='satTrack.sensor')),
            ],
        ),
    ]
