# Generated by Django 4.1.4 on 2023-08-03 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellite',
            old_name='tle',
            new_name='tle_now',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), verbose_name='Launch Date'),
        ),
    ]
