# Generated by Django 4.1.4 on 2023-08-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0003_tle'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='orbit_distance',
            field=models.FloatField(default=0, verbose_name='Successive orbits distance [km]'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='orbit_revisit',
            field=models.IntegerField(default=0, verbose_name='Revisit Period [days]'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='orbits_per_day',
            field=models.IntegerField(default=0, verbose_name='Orbits per day'),
        ),
    ]
