# Generated by Django 4.1.4 on 2023-08-03 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0004_satellite_orbit_distance_satellite_orbit_revisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), verbose_name='Fech datetime'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='tle',
            field=models.TextField(default='', max_length=100, verbose_name='Satellite Tle '),
        ),
    ]
