# Generated by Django 4.1.4 on 2023-07-31 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0004_alter_satellite_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='tilting_type',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 19, 57, 57, 887819), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 31, 19, 57, 57, 887819), verbose_name='Launch Date'),
        ),
    ]
