# Generated by Django 4.1.4 on 2023-08-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0005_alter_tle_date_added_alter_tle_satellite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tle',
            name='satellite',
        ),
        migrations.RemoveField(
            model_name='tle',
            name='tle',
        ),
    ]
