# Generated by Django 4.1.4 on 2023-08-03 12:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0006_remove_tle_date_added_remove_tle_satellite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), null=True, verbose_name='Fech datetime'),
        ),
        migrations.AddField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite'),
        ),
        migrations.AddField(
            model_name='tle',
            name='tle',
            field=models.TextField(default=None, max_length=100, null=True, verbose_name='Satellite Tle '),
        ),
    ]
