# Generated by Django 4.1.4 on 2023-08-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0007_tle_date_added_tle_satellite_tle_tle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite'),
        ),
        migrations.AlterField(
            model_name='tle',
            name='tle',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='Satellite Tle '),
        ),
    ]
