# Generated by Django 4.1.4 on 2023-08-03 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0008_alter_tle_satellite_alter_tle_tle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), null=True, verbose_name='Fech datetime '),
        ),
        migrations.AlterField(
            model_name='tle',
            name='tle',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='Satellite Tle'),
        ),
    ]
