# Generated by Django 4.1.4 on 2023-08-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0009_alter_tle_date_added_alter_tle_tle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(default={'name': ''}, on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite'),
        ),
    ]
