# Generated by Django 4.1.4 on 2023-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0011_alter_tle_satellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tle',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='tle',
            name='satellite',
        ),
        migrations.AlterField(
            model_name='tle',
            name='tle',
            field=models.TextField(default='s', max_length=100, null=True, verbose_name='Satellite Tle'),
        ),
    ]
