# Generated by Django 4.1.4 on 2023-08-03 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0012_remove_tle_date_added_remove_tle_satellite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2000, 2, 2, 2, 2, 2, 2), null=True, verbose_name='Fech datetime '),
        ),
        migrations.AddField(
            model_name='tle',
            name='satellite',
            field=models.ForeignKey(default={'name': '', 'norad_id': 0}, on_delete=django.db.models.deletion.CASCADE, to='satTrack.satellite'),
        ),
    ]
