# Generated by Django 4.1.4 on 2023-08-03 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0014_alter_tle_satellite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TLE',
        ),
    ]
