# Generated by Django 4.1.4 on 2023-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0017_remove_tle_date_added_tle_epoch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tle',
            name='tle',
            field=models.TextField(default='s', max_length=300, null=True, verbose_name='Satellite Tle'),
        ),
    ]
